### ISSUE TITLE
A4.2.a: Implement health check feature

### ISSUE THREAD

**Issue by jesvarzam** [gii-is-psg2/PSG2-2021-G4-41#58]
As a group, create a new feature in your Petclinic application that provides a health check. This feature has to be implemented using the branching strategy defined in the Sprint S2. Regarding security, the health check endpoint should be accessible without authentication.

**Comment by JSnow11** [comment]
## description
 As a group, create a new feature in your Petclinic application that provides a health check. This feature has to be implemented using the branching strategy defined in the Sprint S2. Regarding security, the health check endpoint should be accessible without authentication.

## to-do
- [ ] implement the health check feature
- [ ] ensure accesibility

## acceptance 
- [ ] health service available for everyone

**Comment by JSnow11** [comment]
## first functional version
- actuator/health endpoint is live
- it's returning UP when the application is correctly serving

![image](https://user-images.githubusercontent.com/47798577/118020628-95684800-b35a-11eb-927a-6a6bc5a46bcc.png)
