### ISSUE TITLE
A4.2.b: Create a release and deploy the application in Heroku

### ISSUE THREAD

**Issue by jesvarzam** [gii-is-psg2/PSG2-2021-G4-41#59]
## description

After its implementation, a new release has to be created according to the branching strategy of the group. 

As a result of that release, the Petclinic application has to be deployed in **Heroku**, accessible under the URL https://psg2-2021-gx-xy.herokuapp.com/, where X-XY corresponds to the group ID.

## accept
- [x] app live on https://psg2-2021-g2-41.herokuapp.com/

**Comment by JSnow11** [comment]
## app live
https://psg2-2021-g4-41.herokuapp.com/
